#!/bin/bash

for folder in `find . -name errors | awk '{ print $0"/" }'`; do
	echo Clear errors in $folder
    	rm -fr $folder/*
done

# Clear all sessions
for folder in `find . -name sessions | awk '{ print $0"/" }'`; do
	echo Clear sessions in $folder
    	rm -fr $folder/*
done

rm -fr ./apps/temp_*
