#!/bin/bash

PYTHON=python3.10
# CHECK PYTHON 3
if command -v $PYTHON &>/dev/null; then
    echo ${PYTHON} available
else
    echo ${PYTHON} not available, please install it or add to the PATH variable
    exit 1
fi

# CHECK distutils
if ${PYTHON} -c "import distutils.cmd" &>/dev/null; then
    echo ${PYTHON} distutils module is available
else
    echo ${PYTHON} distutils module is not available, please install it or add to the PYTHONPATH variable
    echo For example in ubuntu it needs to execute: sudo apt install ${PYTHON}-distutils
    exit 1
fi

# CHECK VIRTUALENV COMMAND
if command -v ${PYTHON} -m venv &>/dev/null; then
    echo Venv command available
else
    echo Venv not available, please install it [For example: ${PYTHON} -m pip install python-venv]
    exit 1
fi

COMMAND=$1
PYTHON_VERSION=3.10
while [[ "$#" -gt 0 ]]; do
    case $1 in
    --python-version)
        PYTHON_VERSION="$2"
        shift
        shift
        ;;
    *)
        COMMAND=$1
        shift
        break
        ;;
    esac
    shift
done
# CHECK VENV NOT EXISTS
if [ ! -d .venv ]; then

    $PYTHON -m venv .venv
    if [ ! -d .pip ]; then
        mkdir .pip
        curl https://bootstrap.pypa.io/get-pip.py -o .pip/get-pip.py
    fi
    .venv/bin/python3 .pip/get-pip.py
    .venv/bin/pip3 install -r requirements.txt
    .venv/bin/pip3 install -r requirements-tests.txt
    .venv/bin/pip3 install -r requirements-dev.txt
fi

if [ -f '.env' ]; then
    echo Use .env file to read sensitive information
    while IPS='=' read -r key value; do
        eval ${key}
    done <'.env'
else
    # REGENERATE SENSITIVE INFO FROM TEMPLATE
    cat >'.env' <<EOF
HTTP_PORT=8024
HTTP_HOST=0.0.0.0
PYTHONPATH=.
EOF
fi

echo EXECUTE
echo =========== $COMMAND
echo $COMMAND ===========
echo COMMAND

if [ "x$COMMAND" == "xmanage" ]; then
    echo "Run manage.py script manage.py $@"
    # Sample: ./buildew manage loaddata app_moods/fixtures/geometry_shapes.yaml
    export DJANGO_SECRET_KEY=$(.venv/bin/python3 -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())')
    export DJANGO_DEBUG=True
    export PYTHONPATH=${PYTHONPATH}

    .venv/bin/python3 manage.py $@
fi

if [ "x$COMMAND" == "xredeps" ]; then
    echo "Reinstall dependencies"
    .venv/bin/pip3 install -r requirements.txt
    .venv/bin/pip3 install -r requirements-tests.txt
    .venv/bin/pip3 install -r requirements-dev.txt
fi

if [ "x$COMMAND" == "xclean" ]; then
    echo "Clean temporary folders"
    find . -name __pycache__ | xargs rm -fr
fi

if [ "x$COMMAND" == "xrun" ]; then
    echo 'Run site'
    export PYTHONPATH=${PYTHONPATH}
    export HTTP_PORT=${HTTP_PORT}
    export HTTP_HOST=${HTTP_HOST}
    .venv/bin/uvicorn --port ${HTTP_PORT} --host ${HTTP_HOST} service.tm:app --reload
fi

AVAILABLE_COMMANDS="run publish manage redeps clean"
echo ''
[[ $AVAILABLE_COMMANDS =~ (^| )$COMMAND($| ) ]] && echo 'Ok' || echo 'Unknown command: ' "$COMMAND" && echo 'Available commands are: ' "$AVAILABLE_COMMANDS"
